site_name: SIMUREX 2026 – pyViewFactor
site_url: https://matbog.github.io/simurex2026-pvf/
site_description: IBPSA 2026 - Ecole thématique SIMUREX - sessoin calcul des facteurs de forme
repo_url: https://github.com/matbog/simurex2026-pvf
repo_name: matbog/simurex2026-pvf

theme:
  name: material
  language: fr
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: white
      accent: pink
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
extra_css:
  - assets/extra.css
  
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Quick Start: get-started.md
  - Rappel Scientifiques: scientific-background.md
  - Exercices & Mini-Project: exercises.md
  - A propos de pyviewfactor: about-pyviewfactor.md
